baseURL = "blog.alexsanjoseph.com/"
languageCode = "en"
title = "Alex's Blog"
theme = "hyde-hyde"

## Hugo Built-in Features
# googleAnalytics = "your-google-analytics-id"
enableRobotsTXT = true

# summarylength = 30

# paginate = 5

## Site Settings
[params]
    author = "Alex"
    title = "Alex's"

    sidebar-width = "36 rem"

    authorimage = "/img/alex.jpeg"
    dateformat = "2006 Jan 2"

    # sidebar, copyright & license
    copyright = "alexsanjoseph"
    since = 2016
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    showBuiltWith = true

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"

    # Table of contents
    #toc = none, "hugo", or "tocbot"
    # toc = "tocbot"

## Social Accounts
[params.social]
    github = "alexsanjoseph"
    linkedin = "alexsanjoseph"
    twitter = "alexsanjoseph"
    stackoverflow = "1653808/alex-joseph"
    email = "alexsanjoseph at gmail.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
# [[menu.main]]
#     name = "Portfolio"
#     identifier = "portfolio"
#     weight = 200
#     url = "/portfolio/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"